apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-mssql-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: sonar-mssql-pv
