apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar
spec:
  selector:
    matchLabels:
      app: sonar
  replicas: 1
  template:
    metadata:
      name: sonar
      labels:
        app: sonar
    spec:
      containers:
        - name: sonar
          image: sonarqube:6.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
              name: sonarport
          env:
            - name: SONARQUBE_JDBC_USERNAME
              value: sa
            - name: SONARQUBE_JDBC_PASSWORD
              value: password
            - name: SONARQUBE_JDBC_URL
              value: jdbc:mssql://mssql-db:1433/sonar_db
---
kind: Service
apiVersion: v1
metadata:
  name: sonar
  labels:
    app: sonar
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9000
      name: sonarport
  selector:
    app: sonar
    type: LoadBalancer
